PAWQ-55: crear la interfaz formulario de aptitud con los campos necesarios y el boton de envio
TIC-2023-GMC/FrontEnd-TIC-2023-GMC pull request #21
Opened 2023-08-13 00:07 UTC by GandhyCrush

2023-08-13 19:40 UTC, Erickneitor1416 requested changes

2023-08-13 19:40 UTC, Erickneitor1416 commented on src/Screens/User/UserAptitudeScreenForm.tsx
> +		updateUserMutation.mutate(updatedUser);
agregar el uso de la funcion setUser del contexto para actualizar el usuario local

2023-08-13 19:40 UTC, Erickneitor1416 commented on src/navigation/SocialNavigator.tsx
> +			<Stack.Screen name="Profile" component={ProfileScreen} />
agregar la lógica para eliminar headers duplicados, se puede usar la misma logica de noTabBarRoutes

2023-08-14 00:29 UTC, GandhyCrush commented on src/Screens/User/UserAptitudeScreenForm.tsx
> +		updateUserMutation.mutate(updatedUser);
Please check last push

2023-08-14 00:30 UTC, GandhyCrush commented on src/navigation/SocialNavigator.tsx
> +			<Stack.Screen name="Profile" component={ProfileScreen} />
Please, check last push

2023-08-14 00:52 UTC, Erickneitor1416 approved these changes

2023-08-14 00:53 UTC, merged